### PR TITLE
CIF-864 - Virtual folder title not shown in folder properties

### PR DESCRIPTION
**Pull request by cjelger**
- fixed missing title
- added category id property
- removed useless system properties

## How Has This Been Tested?

We don't have ITs yet, it cannot be tested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Comment by LSantha** [comment]
@cjelger , I had an idea for solving this based on deep read value map. Then it wouldn't matter if you have "./property" or "property" in your dialog. It should also work for the product tree root.

**Comment by cjelger** [comment]
@LSantha feel free to take the issue over if you want to fix it differently

**Review by herzog31 — APPROVED** [review]

**Review by LSantha — APPROVED** [review]
It's very likely that we don't need those fields, so this PR is OK.
I can improve the resource provider next week to also accept "./property".

**Comment by cjelger** [comment]
I'll wait until @herzog31 merges the ITs, I think this fix will break one test because we had a `TODO` test that checked that this didn't work ;-)

**Pull request merged**
