### PR TITLE
CIF-842 - fix product description mapping

### PR DESCRIPTION
**Pull request by mhaack**
## Description

Fixes product description mapping.

## Related Issue

CIF-842

## Motivation and Context

Fixes product description mapping, which was wrong and returned the object id before.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Review by cjelger — APPROVED** [review]

**Comment by herzog31** [comment]
@cjelger @mhaack don't we have the same NPE problem here like in https://github.com/adobe/aem-core-cif-components/pull/5?

**Comment by cjelger** [comment]
Good point, yes we should probably check that.

**Comment by mhaack** [comment]
I tested with products which have a description and with products without description, both worked and no error.

**Comment by mhaack** [comment]
Just double checked in the debugger. The query returns an empty string from products without description. GraphQL always has the object, if no description is present it returns ```"description": {
              "html": ""
            }```.

**Pull request merged**
