### PR TITLE
CIF-993 - Extend SKU selection for product variants in product picker

### PR DESCRIPTION
**Pull request by cjelger**
- added an option to return the "base#variant" skus when selecting a product variant

## Motivation and Context

When selecting a variant, we need an option to return the `base#variant` skus because by default, it's not possible to query a variant product in Magento so we need the base product sku to be able to query the product and its variants, and then access the selected variant.

## How Has This Been Tested?

We don't have unit tests for these java files because they belong to a content package, and do not yet UI tests. I tested everything manually.

## Screenshots (if appropriate):

Screenshot 2019-07-25 at 12 35 28

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

### CODE REVIEW

**Review by herzog31 — APPROVED** [review]
LGTM

For me the term `skus` is confusing and I would rather use `variantSku`.

**Comment by cjelger** [comment]
The issue is that it can also just be the sku of the base product, if no variant is selected, so it's not always a "variantSku". But I agree that `sku` vs. `skus` can be misleading, I also thought of `skuChain`   ... I don't really have a preference.

**Review by mhaack — APPROVED** [review]
LGTM.

We should mention explicitly in the readme that `#` can not be used as part of SKU then.

**Comment by mhaack** [comment]
Instead of `skus` we also could use `skuCombination` or `combinedSku`

**Comment by dplaton** [comment]
>We should mention explicitly in the readme that # can not be used as part of SKU

Is this something we can control? Customers establish their own SKUs, don't they?

**Comment by mhaack** [comment]
> Is this something we can control? Customers establish their own SKUs, don't they?

Right, be we use the `#` as a separator here. So if the sku contains one `#` as well it will break eventually the behavior.

**Review by dplaton — APPROVED** [review]

**Pull request merged**
