### PR TITLE
#4 - Products not showing up for some categories in sample catalog

### PR DESCRIPTION
**Pull request by cjelger**
- exclude categories with null url_path from sling resource provider
- removed the temporary code fixing a bug with Magento 2.3.0

## Related Issue

#4 

## How Has This Been Tested?

Extended unit test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Review by herzog31 — APPROVED** [review]

**Comment by LSantha** [comment]
@jelger, doesn't this has the consequence that certain categories will be unreachable in the product console and picker? Would it work to use the category id when category name and url path is missing to make all categories available?

**Comment by mhaack** [comment]
Shouldn't we actually consider this as a Magento (or sample data) bug? At least via the Magento UI one can not create a category without a name and also url_key is set automatically to the name if the field is empty.

**Comment by cjelger** [comment]
Yes it makes these categories unreachable, and yes why not we could in this case use the `id`. This would however require quite some more changes because all the resource path resolution logic is based on the `url_path` like `men/tops-men/jackets-men` which is computed by Magento. If this is `null`, we'd have to manually rebuild something like `men/42/tees-men` so I'd say this is out of scope of this PR.

**Comment by cjelger** [comment]
Actually on my magento instance with sample data, these categories are also not reachable anywhere! ;-)

**Comment by herzog31** [comment]
@mhaack I agree that this is a bug in the Magento samepl data. However, I prefer @cjelger's approach of ignoring the categories and outputting a log message that helps to identify the problem instead of letting the console break or adding a workaround.

**Review by LSantha — APPROVED** [review]

**Review by mhaack — APPROVED** [review]
@herzog31 yes I'm also fine with the current fix ;-)

**Pull request merged**
