### PR TITLE
CIF-1347 - Product Console doesn't display products

### PR DESCRIPTION
**Pull request by LSantha**
* fixed connector to properly read the magentoStore configuration property

## Description

Products are not available in product console when using a Magento store view other than default.

## Related Issue

CIF-1347

## How Has This Been Tested?

Manually.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Review by herzog31 — COMMENTED** [review]
There are still some occurrences of `cq:magentoStore`, especially in tests that need to be cleaned up. Also please add a test to make sure this bug is detected early the next time.

**Comment by LSantha** [comment]
There are occurrences of cq:magentoStore only in tests besides that one which was added now to the code for backwards compatibility with the old configurations. The tests with occurrences are covering cases of backwards compatibility.

**Review by dplaton — APPROVED** [review]

**Comment by dkuntze** [comment]
Wouldn't the better fix be to change the .content.xml that sets this property to the existing value vs this new value - thereby keeping any legacy code operating as is?

**Comment by LSantha** [comment]
@dkuntze , this PR ensures backwards compatibility by using the old property name at the old location. The new property name is used only at the new location of the configuration.

**Pull request merged**
